services:
  patient-service:
    container_name: patient-service
    build:
      context: ./patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient_db:5432/patient_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
      BILLING_SERVICE_ADDRESS: billing-service
      BILLING_SERVICE_GRPC_PORT: 9001
    networks:
      - patient-network

  billing-service:
    container_name: billing-service
    build:
      context: ./billing-service
    ports:
      - "4001:4001"
      - "9001:9001"
    networks:
      - patient-network


networks:
  patient-network:
    external: true