services:
  patient-service:
    container_name: patient-service
    build:
      context: ./patient-service
    ports:
      - "4000:4000"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://patient_db:5432/patient_db
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: password
    networks:
      - patient-network

networks:
  patient-network:
    external: true