#H2 variant

#spring.application.name=patient-service
#
#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:testdb
#spring.datasource.driverClassName=org.h2.Driver
#spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
#
#spring.datasource.username=admin
#spring.datasource.password=password
#
#spring.jpa.hibernate.ddl-auto=update
#spring.sql.init.mode=always
#spring.jpa.defer-datasource-initialization=true
#
#server.port=4000
#
#logging.level.root=infok






#PostgreSQL variant

spring.application.name=patient-service

spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5000}/patient_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=admin
spring.datasource.password=password

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

server.port=4000

logging.level.root=info

billing.service.address=billing-service
billing.service.grpc.port=9001

spring.kafka.bootstrap-servers=kafka:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer